FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=903090
ENV MYSQL_DATABASE=securetest
ENV MYSQL_USER=sajal
ENV MYSQL_PASSWORD=merai@Iui1234

# Expose the MySQL port
EXPOSE 3308
