# version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql_container1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 903090
      MYSQL_DATABASE: securetest
      MYSQL_USER: sajal
      MYSQL_PASSWORD: merai@Iui1234
    ports:
      - "3306:3306"
